InsuranceAgency/Models/Service.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace InsuranceAgency.Models
{
    [Table("Services")]
    public class Service
    {
        [Key] public int Id { get; set; }
        [Required]
        [StringLength(100)]
        public string InsuranceObjectType { get; set; }
        [Required]
        [Column(TypeName = "decimal(18,2)")]
        [Range(0.01, 1000000.00, ErrorMessage = "Значение должно быть от 0.01 до 1,000,000.00.")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:0.00}")]
        public decimal PremiumCoef {  get; set; }
        [Required]
        [Column(TypeName = "decimal(18,2)")]
        [Range(0.01, 1000000.00, ErrorMessage = "Значение должно быть от 0.01 до 1,000,000.00.")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:0.00}")]
        public decimal PaymentCoef { get; set;}
    }
}

InsuranceAgency/Controllers/PolicyClaimsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using InsuranceAgency.Data;
using InsuranceAgency.Models;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;

namespace InsuranceAgency.Controllers
{
    [Authorize(Roles = "Administrator, InsuranceAgent, Client")]
    public class PolicyClaimsController : Controller
    {
        private readonly InsuranceAgencyDbContext _context;

        public PolicyClaimsController(InsuranceAgencyDbContext context)
        {
            _context = context;
        }
        [Authorize(Roles = "Administrator, InsuranceAgent")]
        // GET: PolicyClaims
        public async Task<IActionResult> Index()
        {
            var insuranceAgencyDbContext = _context.PolicyClaims.Include(p => p.Client).Include(p => p.InsuranceObject).Include(p => p.Service).OrderByDescending(p => p.ClaimDate);
            return View(await insuranceAgencyDbContext.ToListAsync());
        }
        [Authorize(Roles = "Administrator, InsuranceAgent")]
        // GET: PolicyClaims/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.PolicyClaims == null)
            {
                return NotFound();
            }

            var policyClaim = await _context.PolicyClaims
                .Include(p => p.Client)
                .Include(p => p.InsuranceObject)
                .Include(p => p.Service)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (policyClaim == null)
            {
                return NotFound();
            }

            return View(policyClaim);
        }
        [Authorize(Roles = "Administrator")]
        // GET: PolicyClaims/Create
        public IActionResult Create()
        {
            ViewData["ClientId"] = new SelectList(_context.Clients, "Id", "Email");
            ViewData["InsuranceObjectId"] = new SelectList(_context.InsuranceObjects, "Id", "Type");
            ViewData["ServiceId"] = new SelectList(_context.Services, "Id", "InsuranceObjectType");
            return View();
        }
        [Authorize(Roles = "Administrator")]
        // POST: PolicyClaims/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ServiceId,InsuranceObjectId,ClientId,Id,Description,ClaimDate,ClaimStatus")] PolicyClaim policyClaim)
        {
            if (ModelState.IsValid)
            {
                _context.Add(policyClaim);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClientId"] = new SelectList(_context.Clients, "Id", "Email", policyClaim.ClientId);
            ViewData["InsuranceObjectId"] = new SelectList(_context.InsuranceObjects, "Id", "Type", policyClaim.InsuranceObjectId);
            ViewData["ServiceId"] = new SelectList(_context.Services, "Id", "InsuranceObjectType", policyClaim.ServiceId);
            return View(policyClaim);
        }
        [Authorize(Roles = "Administrator")]
        // GET: PolicyClaims/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.PolicyClaims == null)
            {
                return NotFound();
            }

            var policyClaim = await _context.PolicyClaims.FindAsync(id);
            if (policyClaim == null)
            {
                return NotFound();
            }
            ViewData["ClientId"] = new SelectList(_context.Clients, "Id", "Email", policyClaim.ClientId);
            ViewData["InsuranceObjectId"] = new SelectList(_context.InsuranceObjects, "Id", "Type", policyClaim.InsuranceObjectId);
            ViewData["ServiceId"] = new SelectList(_context.Services, "Id", "InsuranceObjectType", policyClaim.ServiceId);
            return View(policyClaim);
        }
        [Authorize(Roles = "Administrator")]
        // POST: PolicyClaims/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ServiceId,InsuranceObjectId,ClientId,Id,Description,ClaimDate,ClaimStatus")] PolicyClaim policyClaim)
        {
            if (id != policyClaim.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(policyClaim);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PolicyClaimExists(policyClaim.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClientId"] = new SelectList(_context.Clients, "Id", "Email", policyClaim.ClientId);
            ViewData["InsuranceObjectId"] = new SelectList(_context.InsuranceObjects, "Id", "Type", policyClaim.InsuranceObjectId);
            ViewData["ServiceId"] = new SelectList(_context.Services, "Id", "InsuranceObjectType", policyClaim.ServiceId);
            return View(policyClaim);
        }
        [Authorize(Roles = "Administrator")]
        // GET: PolicyClaims/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.PolicyClaims == null)
            {
                return NotFound();
            }

            var policyClaim = await _context.PolicyClaims
                .Include(p => p.Client)
                .Include(p => p.InsuranceObject)
                .Include(p => p.Service)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (policyClaim == null)
            {
                return NotFound();
            }

            return View(policyClaim);
        }
        [Authorize(Roles = "Administrator")]
        // POST: PolicyClaims/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.PolicyClaims == null)
            {
                return Problem("Entity set 'InsuranceAgencyDbContext.PolicyClaims'  is null.");
            }
            var policyClaim = await _context.PolicyClaims.FindAsync(id);
            if (policyClaim != null)
            {
                _context.PolicyClaims.Remove(policyClaim);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        [Authorize(Roles = "Administrator, InsuranceAgent")]
        // AJAX Filter: Search by ClaimStatus
        [HttpGet]
        public async Task<IActionResult> FilterByStatus(ClaimStatus? status, string searchQuery)
        {
            var filteredClaims = _context.PolicyClaims
                .Include(p => p.Client)
                .Include(p => p.InsuranceObject)
                .Include(p => p.Service)
                .AsQueryable();

            if (status.HasValue)
            {
                filteredClaims = filteredClaims.Where(c => c.ClaimStatus == status.Value);
            }

            if (!string.IsNullOrEmpty(searchQuery))
            {
                filteredClaims = filteredClaims.Where(c =>
                    c.Client.Name.Contains(searchQuery) ||
                    c.Client.Surname.Contains(searchQuery) ||
                    c.Client.Patronymic.Contains(searchQuery) ||
                    c.Client.Email.Contains(searchQuery));
            }

            return PartialView("_PolicyClaimsTable", await filteredClaims.ToListAsync());
        }
        [Authorize(Roles = "Administrator, InsuranceAgent")]
        // POST: PolicyClaims/UpdateStatus
        [HttpPost]
        public async Task<IActionResult> UpdateStatus(int id, ClaimStatus newStatus)
        {
            var claim = await _context.PolicyClaims.Include(c => c.Service).Include(c => c.InsuranceObject).FirstOrDefaultAsync(c => c.Id == id);
            if (claim == null) return NotFound();

            // Check and handle status changes
            switch (newStatus)
            {
                case ClaimStatus.Одобрена:
                    claim.ClaimStatus = newStatus;
                    break;
                case ClaimStatus.Отклонена:
                    claim.ClaimStatus = newStatus;
                    break;
                case ClaimStatus.Обрабатывается: 
                    claim.ClaimStatus = newStatus;
                    break;
                case ClaimStatus.Завершена:
                    if (claim.ClaimStatus == ClaimStatus.Оплачена)
                    {
                        // Create Policy
                        var policy = new Policy
                        {
                            Type = Policy.Types(claim.Service.InsuranceObjectType),
                            StartDate = DateTime.Now,
                            EndDate = DateTime.Now.AddYears(1),
                            PremiumAmount = claim.InsuranceObject.Price * claim.Service.PremiumCoef,
                            PaymentCoef = claim.Service.PaymentCoef,
                            Status = PolicyStatus.Активен,
                            InsuranceObjectId = claim.InsuranceObjectId,

InsuranceAgency/Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using InsuranceAgency.Data;
using InsuranceAgency.Models;
using Microsoft.AspNetCore.Authorization;

namespace InsuranceAgency.Controllers
{
    public class ServicesController : Controller
    {
        private readonly InsuranceAgencyDbContext _context;

        public ServicesController(InsuranceAgencyDbContext context)
        {
            _context = context;
        }
        // GET: Services
        public async Task<IActionResult> Index()
        {
              return _context.Services != null ? 
                          View(await _context.Services.ToListAsync()) :
                          Problem("Entity set 'InsuranceAgencyDbContext.Services'  is null.");
        }
        // GET: Services/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Services == null)
            {
                return NotFound();
            }

            var service = await _context.Services
                .FirstOrDefaultAsync(m => m.Id == id);
            if (service == null)
            {
                return NotFound();
            }

            return View(service);
        }
        [Authorize(Roles = "Administrator, InsuranceAgent")]
        // GET: Services/Create
        public IActionResult Create()
        {
            return View();
        }
        [Authorize(Roles = "Administrator, InsuranceAgent")]
        // POST: Services/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,InsuranceObjectType,PremiumCoef,PaymentCoef")] Service service)
        {
            if (ModelState.IsValid)
            {
                _context.Add(service);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(service);
        }
        [Authorize(Roles = "Administrator, InsuranceAgent")]
        // GET: Services/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Services == null)
            {
                return NotFound();
            }

            var service = await _context.Services.FindAsync(id);
            if (service == null)
            {
                return NotFound();
            }
            return View(service);
        }
        [Authorize(Roles = "Administrator, InsuranceAgent")]
        // POST: Services/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,InsuranceObjectType,PremiumCoef,PaymentCoef")] Service service)
        {
            if (id != service.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(service);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ServiceExists(service.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(service);
        }
        [Authorize(Roles = "Administrator")]
        // GET: Services/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Services == null)
            {
                return NotFound();
            }

            var service = await _context.Services
                .FirstOrDefaultAsync(m => m.Id == id);
            if (service == null)
            {
                return NotFound();
            }

            return View(service);
        }

        [Authorize(Roles = "Administrator")]
        // POST: Services/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Services == null)
            {
                return Problem("Entity set 'InsuranceAgencyDbContext.Services'  is null.");
            }
            var service = await _context.Services.FindAsync(id);
            if (service != null)
            {
                _context.Services.Remove(service);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        private bool ServiceExists(int id)
        {
          return (_context.Services?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

InsuranceAgency/Views/Services/Create.cshtml
@model InsuranceAgency.Models.Service

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Service</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="InsuranceObjectType" class="control-label"></label>
                <input asp-for="InsuranceObjectType" class="form-control" />
                <span asp-validation-for="InsuranceObjectType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PremiumCoef" class="control-label"></label>
                <input asp-for="PremiumCoef" class="form-control" />
                <span asp-validation-for="PremiumCoef" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PaymentCoef" class="control-label"></label>
                <input asp-for="PaymentCoef" class="form-control" />
                <span asp-validation-for="PaymentCoef" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.5/dist/jquery.validate.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.5/dist/localization/messages_ru.js"></script>
    <script>
        $(document).ready(function () {
            $.validator.methods.range = function (value, element, param) {
                var globalizedValue = value.replace(",", "."); // Заменяем запятую на точку
                return this.optional(element) || (globalizedValue >= param[0] && globalizedValue <= param[1]);
            };

            $.validator.methods.number = function (value, element) {
                return this.optional(element) || /^-?\d+(\.\d+)?$/.test(value.replace(",", "."));
            };
        });

    </script>
}

InsuranceAgency/Views/Services/Delete.cshtml
@model InsuranceAgency.Models.Service

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Service</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.InsuranceObjectType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InsuranceObjectType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PremiumCoef)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PremiumCoef)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PaymentCoef)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PaymentCoef)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

InsuranceAgency/Views/Services/Details.cshtml
@model InsuranceAgency.Models.Service

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Service</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.InsuranceObjectType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InsuranceObjectType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PremiumCoef)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PremiumCoef)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PaymentCoef)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PaymentCoef)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

InsuranceAgency/Views/Services/Edit.cshtml
@model InsuranceAgency.Models.Service

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Service</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="InsuranceObjectType" class="control-label"></label>
                <input asp-for="InsuranceObjectType" class="form-control" />
                <span asp-validation-for="InsuranceObjectType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PremiumCoef" class="control-label"></label>
                <input asp-for="PremiumCoef" class="form-control" />
                <span asp-validation-for="PremiumCoef" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PaymentCoef" class="control-label"></label>
                <input asp-for="PaymentCoef" class="form-control" />
                <span asp-validation-for="PaymentCoef" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.5/dist/jquery.validate.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.5/dist/localization/messages_ru.js"></script>
    <script>
        $(document).ready(function () {
            $.validator.methods.range = function (value, element, param) {
                var globalizedValue = value.replace(",", "."); // Заменяем запятую на точку
                return this.optional(element) || (globalizedValue >= param[0] && globalizedValue <= param[1]);
            };

            $.validator.methods.number = function (value, element) {
                return this.optional(element) || /^-?\d+(\.\d+)?$/.test(value.replace(",", "."));
            };
        });

    </script>
}

InsuranceAgency/Views/Services/Index.cshtml
@model IEnumerable<InsuranceAgency.Models.Service>

@{
    ViewData["Title"] = "Index";
}

<h1>Услуги</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.InsuranceObjectType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PremiumCoef)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PaymentCoef)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.InsuranceObjectType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PremiumCoef)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PaymentCoef)
            </td>
            <td>
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                @if(User.IsInRole("Administrator")){
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a><p>|</p>
                    
                }
                @if (User.IsInRole("InsuranceAgent") || User.IsInRole("Administrator"))
                {
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                }
                    @if (User.IsInRole("Client"))
                    {
                        <a asp-action="CreatePolicyClaimWithObject"
                           asp-controller="PolicyClaims"
                           asp-route-serviceId="@item.Id"
                           asp-route-clientId="@User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier).Value">
                            Подать заявку
                        </a>
                    }
            </td>
        </tr>
}
    </tbody>
</table>