InsuranceAgency/Models/Claim.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace InsuranceAgency.Models
{
    public abstract class Claim
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(200)]
        public string Description { get; set; }
        [Required]
        [Column(TypeName = "DATE")]
        public DateOnly ClaimDate { get; set; }
        [Required]
        public ClaimStatus ClaimStatus { get; set; }
    }
    public enum ClaimStatus
    {
        Создана = 1,
        Обрабатывается = 2,
        Одобрена = 3,
        Отклонена = 4,
        Подписана = 5,
        Оплачена = 6,
        Завершена = 7
    }
}

InsuranceAgency/Models/PaymentClaim.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace InsuranceAgency.Models
{
    [Table("PaymentClaims")]
    public class PaymentClaim:Claim
    {
        [Required]
        [Column(TypeName ="decimal(18,2)")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:0.00}")]
        public decimal ClaimAmount {  get; set; }
        [Required]
        [StringLength(100)]
        public string ClientBankAccount { get; set; }
        [Required]
        [ForeignKey("Policy")]
        public int PolicyId {  get; set; }
        [ValidateNever]
        public Policy Policy { get; set; }
        [Required]
        [ForeignKey("Client")]
        public int ClientId {  get; set; }
        [ValidateNever]
        public Client Client { get; set; }
    }
}

InsuranceAgency/Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using InsuranceAgency.Data;
using InsuranceAgency.Models;
using Microsoft.AspNetCore.Authorization;

namespace InsuranceAgency.Controllers
{
    [Authorize(Roles = "Administrator, InsuranceAgent, Accountant")]
    public class ClientsController : Controller
    {
        private readonly InsuranceAgencyDbContext _context;

        public ClientsController(InsuranceAgencyDbContext context)
        {
            _context = context;
        }

        // GET: Clients
        public async Task<IActionResult> Index()
        {
              return _context.Clients != null ? 
                          View(await _context.Clients.ToListAsync()) :
                          Problem("Entity set 'InsuranceAgencyDbContext.Clients'  is null.");
        }

        // GET: Clients/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Clients == null)
            {
                return NotFound();
            }

            var client = await _context.Clients
                .FirstOrDefaultAsync(m => m.Id == id);
            if (client == null)
            {
                return NotFound();
            }

            return View(client);
        }

        // GET: Clients/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Clients/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Login,Password,Surname,Name,Patronymic,Email,PhoneNumber,Role")] Client client)
        {
            if (ModelState.IsValid)
            {
                client.Password = BCrypt.Net.BCrypt.HashPassword(client.Password);
                _context.Add(client);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(client);
        }
        [Authorize(Roles = "Administrator")]
        // GET: Clients/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Clients == null)
            {
                return NotFound();
            }

            var client = await _context.Clients.FindAsync(id);
            if (client == null)
            {
                return NotFound();
            }
            return View(client);
        }
        [Authorize(Roles = "Administrator")]
        // POST: Clients/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Login,Password,Surname,Name,Patronymic,Email,PhoneNumber,Role")] Client client)
        {
            if (id != client.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    client.Password = BCrypt.Net.BCrypt.HashPassword(client.Password);
                    _context.Update(client);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClientExists(client.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(client);
        }
        [Authorize(Roles = "Administrator")]
        // GET: Clients/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Clients == null)
            {
                return NotFound();
            }

            var client = await _context.Clients
                .FirstOrDefaultAsync(m => m.Id == id);
            if (client == null)
            {
                return NotFound();
            }

            return View(client);
        }
        [Authorize(Roles = "Administrator")]
        // POST: Clients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Clients == null)
            {
                return Problem("Entity set 'InsuranceAgencyDbContext.Clients'  is null.");
            }
            var client = await _context.Clients.FindAsync(id);
            if (client != null)
            {
                _context.Clients.Remove(client);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClientExists(int id)
        {
          return (_context.Clients?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

InsuranceAgency/Controllers/PaymentClaimsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using InsuranceAgency.Data;
using InsuranceAgency.Models;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;

namespace InsuranceAgency.Controllers
{
    [Authorize(Roles = "Administrator, InsuranceAgent, Accountant, Client")]
    public class PaymentClaimsController : Controller
    {
        private readonly InsuranceAgencyDbContext _context;

        public PaymentClaimsController(InsuranceAgencyDbContext context)
        {
            _context = context;
        }
        [Authorize(Roles = "Administrator, InsuranceAgent, Accountant")]
        // GET: PaymentClaims
        public async Task<IActionResult> Index()
        {
            var insuranceAgencyDbContext = _context.PaymentClaims.Include(p => p.Client).Include(p => p.Policy).OrderByDescending(p => p.ClaimDate);
            return View(await insuranceAgencyDbContext.ToListAsync());
        }
        [Authorize(Roles = "Administrator, InsuranceAgent, Accountant")]
        // GET: PaymentClaims/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.PaymentClaims == null)
            {
                return NotFound();
            }

            var paymentClaim = await _context.PaymentClaims
                .Include(p => p.Client)
                .Include(p => p.Policy)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (paymentClaim == null)
            {
                return NotFound();
            }

            return View(paymentClaim);
        }
        [Authorize(Roles = "Administrator")]
        // GET: PaymentClaims/Create
        public IActionResult Create()
        {
            ViewData["ClientId"] = new SelectList(_context.Clients, "Id", "Email");
            ViewData["PolicyId"] = new SelectList(_context.Policies, "Id", "Type");
            return View();
        }
        [Authorize(Roles = "Administrator")]
        // POST: PaymentClaims/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ClaimAmount,ClientBankAccount,PolicyId,ClientId,Id,Description,ClaimDate,ClaimStatus")] PaymentClaim paymentClaim)
        {
            if (ModelState.IsValid)
            {
                _context.Add(paymentClaim);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClientId"] = new SelectList(_context.Clients, "Id", "Email", paymentClaim.ClientId);
            ViewData["PolicyId"] = new SelectList(_context.Policies, "Id", "Type", paymentClaim.PolicyId);
            return View(paymentClaim);
        }
        [Authorize(Roles = "Administrator")]
        // GET: PaymentClaims/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.PaymentClaims == null)
            {
                return NotFound();
            }

            var paymentClaim = await _context.PaymentClaims.FindAsync(id);
            if (paymentClaim == null)
            {
                return NotFound();
            }
            ViewData["ClientId"] = new SelectList(_context.Clients, "Id", "Email", paymentClaim.ClientId);
            ViewData["PolicyId"] = new SelectList(_context.Policies, "Id", "Type", paymentClaim.PolicyId);
            return View(paymentClaim);
        }
        [Authorize(Roles = "Administrator")]
        // POST: PaymentClaims/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ClaimAmount,ClientBankAccount,PolicyId,ClientId,Id,Description,ClaimDate,ClaimStatus")] PaymentClaim paymentClaim)
        {
            if (id != paymentClaim.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(paymentClaim);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PaymentClaimExists(paymentClaim.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClientId"] = new SelectList(_context.Clients, "Id", "Email", paymentClaim.ClientId);
            ViewData["PolicyId"] = new SelectList(_context.Policies, "Id", "Type", paymentClaim.PolicyId);
            return View(paymentClaim);
        }
        [Authorize(Roles = "Administrator")]
        // GET: PaymentClaims/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.PaymentClaims == null)
            {
                return NotFound();
            }

            var paymentClaim = await _context.PaymentClaims
                .Include(p => p.Client)
                .Include(p => p.Policy)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (paymentClaim == null)
            {
                return NotFound();
            }

            return View(paymentClaim);
        }
        [Authorize(Roles = "Administrator")]
        // POST: PaymentClaims/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.PaymentClaims == null)
            {
                return Problem("Entity set 'InsuranceAgencyDbContext.PaymentClaims'  is null.");
            }
            var paymentClaim = await _context.PaymentClaims.FindAsync(id);
            if (paymentClaim != null)
            {
                _context.PaymentClaims.Remove(paymentClaim);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        [Authorize(Roles = "Administrator,  InsuranceAgent, Accountant")]
        private bool PaymentClaimExists(int id)
        {
          return (_context.PaymentClaims?.Any(e => e.Id == id)).GetValueOrDefault();
        }
        [Authorize(Roles = "Administrator,  InsuranceAgent, Accountant")]
        // Новый метод для AJAX-фильтрации
        [HttpGet]
        public async Task<IActionResult> Filter(string status, string search)
        {
            var claimsQuery = _context.PaymentClaims
                .Include(p => p.Client)
                .Include(p => p.Policy)
                .AsQueryable();

            if (!string.IsNullOrWhiteSpace(status))
            {
                if (Enum.TryParse(status, out ClaimStatus claimStatus))
                {
                    claimsQuery = claimsQuery.Where(c => c.ClaimStatus == claimStatus);
                }
            }

            if (!string.IsNullOrWhiteSpace(search))
            {
                claimsQuery = claimsQuery.Where(c =>
                    EF.Functions.Like(c.Client.Email, $"%{search}%") ||
                    EF.Functions.Like(c.Client.Name + " " + c.Client.Surname + " " + c.Client.Patronymic, $"%{search}%"));
            }

            var filteredClaims = await claimsQuery.ToListAsync();
            return PartialView("_ClaimTable", filteredClaims);
        }
        [Authorize(Roles = "Administrator,  InsuranceAgent, Accountant")]
        // POST: PaymentClaims/UpdateStatus
        [HttpPost]
        public async Task<IActionResult> UpdateStatus(int id, ClaimStatus newStatus)
        {
            var claim = await _context.PaymentClaims.Include(c => c.Policy).Include(c => c.Client).Include(c => c.Policy.InsuranceObject).FirstOrDefaultAsync(c => c.Id == id);
            if (claim == null) return NotFound();

            // Check and handle status changes
            switch (newStatus)
            {
                case ClaimStatus.Одобрена:
                    claim.ClaimStatus = newStatus;
                    break;
                case ClaimStatus.Отклонена:
                    claim.ClaimStatus = newStatus;
                    break;
                case ClaimStatus.Обрабатывается:
                    claim.ClaimStatus = newStatus;
                    break;
                case ClaimStatus.Завершена:
                    claim.ClaimStatus = newStatus;
                    break;
                case ClaimStatus.Оплачена:
                    claim.ClaimStatus = newStatus;
                    break;
            }

            await _context.SaveChangesAsync();
            return Ok();
        }

        //GET: ClientPaymentClaims
        [Authorize(Roles = "Client")]
        public async Task<IActionResult> ClientPaymentClaims()
        {
            // Получаем ID текущего пользователя (предполагается, что он соответствует ClientId)
            var clientId = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier)?.Value;

            if (string.IsNullOrEmpty(clientId) || !int.TryParse(clientId, out int parsedClientId))
            {
                return Unauthorized(); // Если ID клиента не найден, запрещаем доступ
            }

            // Фильтруем платежи по текущему клиенту
            var clientPaymentClaims = await _context.PaymentClaims
                .Include(p => p.Client)
                .Include(p => p.Policy)

InsuranceAgency/Views/PaymentClaims/ClientCreate.cshtml
@model InsuranceAgency.Models.PaymentClaim

@{
    ViewData["Title"] = "Create Payment Claim";
}

<h2>Create Payment Claim</h2>

<form asp-action="ClientCreate" method="post">
    <input type="hidden" asp-for="PolicyId" />

    <div class="form-group">
        <label asp-for="Description" class="control-label"></label>
        <input required asp-for="Description" class="form-control" />
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="ClientBankAccount" class="control-label"></label>
        <input asp-for="ClientBankAccount" class="form-control" />
        <span asp-validation-for="ClientBankAccount" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.5/dist/jquery.validate.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.5/dist/localization/messages_ru.js"></script>
    <script>
        $(document).ready(function () {
            $.validator.methods.range = function (value, element, param) {
                var globalizedValue = value.replace(",", "."); // Заменяем запятую на точку
                return this.optional(element) || (globalizedValue >= param[0] && globalizedValue <= param[1]);
            };

            $.validator.methods.number = function (value, element) {
                return this.optional(element) || /^-?\d+(\.\d+)?$/.test(value.replace(",", "."));
            };
        });

    </script>
}

InsuranceAgency/Views/PaymentClaims/ClientPaymentClaimDetails.cshtml
@model InsuranceAgency.Models.PaymentClaim

@{
    ViewData["Title"] = "Payment Claim Details";
}

<h1>Payment Claim Details</h1>

<div>
    <h4>Claim</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">Description</dt>
        <dd class="col-sm-10">@Model.Description</dd>

        <dt class="col-sm-2">Claim Date</dt>
        <dd class="col-sm-10">@Model.ClaimDate.ToString("dd.MM.yyyy")</dd>

        <dt class="col-sm-2">Status</dt>
        <dd class="col-sm-10">@Model.ClaimStatus</dd>

        <dt class="col-sm-2">Claim Amount</dt>
        <dd class="col-sm-10">@Model.ClaimAmount</dd>

        <dt class="col-sm-2">Client Bank Account</dt>
        <dd class="col-sm-10">@Model.ClientBankAccount</dd>

        <dt class="col-sm-2">Policy</dt>
        <dd class="col-sm-10">@Model.Policy.Type</dd>
    </dl>
    <a asp-action="ClientPaymentClaims" class="btn btn-secondary">Back</a>
</div>

InsuranceAgency/Views/PaymentClaims/ClientPaymentClaims.cshtml
@model IEnumerable<InsuranceAgency.Models.PaymentClaim>

@{
    ViewData["Title"] = "Payment Claims";
}

<h1>Payment Claims</h1>

<table class="table">
    <thead>
        <tr>
            <th>Description</th>
            <th>Claim Date</th>
            <th>Status</th>
            <th>Claim Amount</th>
            <th>Policy</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var claim in Model)
        {
            <tr>
                <td>@claim.Description</td>
                <td>@claim.ClaimDate.ToString("dd.MM.yyyy")</td>
                <td>@claim.ClaimStatus</td>
                <td>@claim.ClaimAmount</td>
                <td>@claim.Policy.Type</td>
                <td>
                    <a asp-action="ClientPaymentClaimDetails" asp-route-id="@claim.Id" class="btn btn-info">Details</a>
                </td>
            </tr>
        }
    </tbody>
</table>

InsuranceAgency/Views/PaymentClaims/Create.cshtml
@model InsuranceAgency.Models.PaymentClaim

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>PaymentClaim</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ClaimAmount" class="control-label"></label>
                <input asp-for="ClaimAmount" class="form-control" />
                <span asp-validation-for="ClaimAmount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClientBankAccount" class="control-label"></label>
                <input asp-for="ClientBankAccount" class="form-control" />
                <span asp-validation-for="ClientBankAccount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PolicyId" class="control-label"></label>
                <select asp-for="PolicyId" class ="form-control" asp-items="ViewBag.PolicyId"></select>
            </div>
            <div class="form-group">
                <label asp-for="ClientId" class="control-label"></label>
                <select asp-for="ClientId" class ="form-control" asp-items="ViewBag.ClientId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClaimDate" class="control-label"></label>
                <input asp-for="ClaimDate" class="form-control" />
                <span asp-validation-for="ClaimDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClaimStatus" class="control-label"></label>
                <select asp-for="ClaimStatus" class="form-control" asp-items="Html.GetEnumSelectList<ClaimStatus>()">
                    <option selected="selected" value="">Please select</option>
                </select>
                <span asp-validation-for="ClaimStatus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.5/dist/jquery.validate.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.5/dist/localization/messages_ru.js"></script>
    <script>
        $(document).ready(function () {
            $.validator.methods.range = function (value, element, param) {
                var globalizedValue = value.replace(",", "."); // Заменяем запятую на точку
                return this.optional(element) || (globalizedValue >= param[0] && globalizedValue <= param[1]);
            };

            $.validator.methods.number = function (value, element) {
                return this.optional(element) || /^-?\d+(\.\d+)?$/.test(value.replace(",", "."));
            };
        });

    </script>
}

InsuranceAgency/Views/PaymentClaims/Delete.cshtml
@model InsuranceAgency.Models.PaymentClaim

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PaymentClaim</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ClaimAmount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ClaimAmount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ClientBankAccount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ClientBankAccount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Policy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Policy.Type)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Client)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Client.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ClaimDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ClaimDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ClaimStatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ClaimStatus)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

InsuranceAgency/Views/PaymentClaims/_ClaimTable.cshtml
@model IEnumerable<InsuranceAgency.Models.PaymentClaim>

<table class="table">
    <thead>
        <tr>
            <th>Сумма заявки</th>
            <th>Банковский счет клиента</th>
            <th>Полис</th>
            <th>Клиент</th>
            <th>Описание</th>
            <th>Дата заявки</th>
            <th>Статус</th>
            <th>Действия</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.ClaimAmount</td>
                <td>@item.ClientBankAccount</td>
                <td><a asp-action="Details" asp-controller="Policies" asp-route-id="@item.PolicyId">@item.Policy.Type</a></td>
                <td>
                    <a asp-action="Details" asp-controller="Clients" asp-route-id="@item.ClientId">
                        @item.Client.Name @item.Client.Surname @item.Client.Patronymic
                        @item.Client.Email
                    </a>
                </td>
                <td>@item.Description</td>
                <td>@item.ClaimDate.ToString("dd.MM.yyyy")</td>
                <td>@item.ClaimStatus</td>
                <td>
                    @if (User.IsInRole("Administrator"))
                    {
                        <a asp-action="Edit" asp-route-id="@item.Id">Изменить</a>
                        <a asp-action="Delete" asp-route-id="@item.Id">Удалить</a>
                    }
                    @if (User.IsInRole("InsuranceAgent"))
                    {
                        if (item.ClaimStatus == InsuranceAgency.Models.ClaimStatus.Создана)
                        {
                            <button class="btn btn-secondary" onclick="updateStatus(@item.Id, 2)">В обработку</button>
                        }
                        else if (item.ClaimStatus == InsuranceAgency.Models.ClaimStatus.Обрабатывается)
                        {
                            <button class="btn btn-secondary" onclick="updateStatus(@item.Id, 3)">Одобрить</button>

                            <button class="btn btn-secondary" onclick="updateStatus(@item.Id, 4)">Отклонить</button>
                        }
                        else if (item.ClaimStatus == InsuranceAgency.Models.ClaimStatus.Оплачена ||
                        item.ClaimStatus == InsuranceAgency.Models.ClaimStatus.Отклонена)
                        {
                            <button class="btn btn-secondary" onclick="updateStatus(@item.Id, 7)">Завершить</button>
                        }
                        else if (item.ClaimStatus == InsuranceAgency.Models.ClaimStatus.Одобрена)
                        {
                            <span>Ожидает оплаты</span>
                        }
                        else if (item.ClaimStatus == InsuranceAgency.Models.ClaimStatus.Подписана)
                        {
                            <span>Ожидает оплаты</span>
                        }
                    }
                    @if (User.IsInRole("Accountant"))
                    {
                        if (item.ClaimStatus == InsuranceAgency.Models.ClaimStatus.Одобрена)
                        {
                            <button class="btn btn-secondary" onclick="updateStatus(@item.Id, 6)">Оплачена</button>
                        }
                    }
                    <a asp-action="Details" asp-route-id="@item.Id">Детали</a>
                </td>
            </tr>
        }
    </tbody>
</table>